
let studs = {
    "Akrishna Agnihotri" : "https://leetcode.com/u/Akrishna_Agnihotri/", 
    "Arpit Saxena" : "https://leetcode.com/u/iarpitsaxena/", 
    "Jeet Thakurela" : "https://leetcode.com/u/jeete1singh/", 
    "Hardik Gupta" : "https://leetcode.com/u/17s3WycoRL/", 
    "Rishabh Sharma" : "https://leetcode.com/u/ps7937164/", 
    "Shivam Chaudhary" : "https://leetcode.com/u/shivam108108/", 
    "Shagun Chaudhary" : "https://leetcode.com/u/shagun_chaudhary/", 
    "Teekam" : "https://leetcode.com/u/z6EmVUzrBN/", 
    "kushagra singh" : "https://leetcode.com/u/kushagra_71/", 
    "Madhav Gaur" : "https://leetcode.com/u/hAG03ejuSY/", 
    "Sahil Gupta" : "https://leetcode.com/u/Sahilgupta21/", 
    "Sneha Agarwal" : "https://leetcode.com/u/snehaagarwal11/", 
    "Srishti Agarwal" : "https://leetcode.com/u/srishti0902/", 
    "ayush srivastav" : "https://leetcode.com/u/ayush_srivastav12/", 
    "Ishan Gupta" : "https://leetcode.com/u/ishangupta_cs22/", 
    "Saubhagya Sharma" : "https://leetcode.com/u/100bhagyasharma/", 
    "Radhika Shrotriya" : "https://leetcode.com/u/Radhika_Shrotriya/", 
    "Surbhi Sharma" : "https://leetcode.com/u/SurbhiSharma12/", 
    "Harsh Gupta" : "https://leetcode.com/u/H_ArS_h/", 
    "Mohan Madhav Singhal" : "https://leetcode.com/u/Mohanmadhavsinghal/", 
    "Vaishnavy manglik" : "https://leetcode.com/u/__vaishnavy/", 
    "Yash Jain" : "https://leetcode.com/u/yjyash0107/", 
    "Deepti Agarwal" : "https://leetcode.com/u/deeptiagarwal16/", 
    "Ditin Agrawal" : "https://leetcode.com/u/ditinagrawal/", 
    "Kirti" : "https://leetcode.com/u/kirtichauhan3963/", 
    "Ekta Agrawal" : "https://leetcode.com/u/agrawalekta625/", 
    "Priyanshi Sharma" : "https://leetcode.com/u/priyanshish2503/", 
    "Vinayak Singh" : "https://leetcode.com/u/vinayak_930/", 
    "Nishant Gupta" : "https://leetcode.com/u/Nishant_Gupta_27/", 
    "Ashish" : "https://leetcode.com/u/Ashish_Dubey1974/", 
    "lokendra singh" : "https://leetcode.com/u/lokiiiii_01/", 
    "Devansh Sharma" : "https://leetcode.com/u/devanshsharm_cs22/", 
    "Saurabh Nagayach" : "https://leetcode.com/u/saurabhnagaich27/", 
    "Hardik Arora" : "https://leetcode.com/u/hardik121/", 
    "Vinay Kumar" : "https://leetcode.com/u/phantom_4669/", 
    "Abhishek Maheshwari" : "https://leetcode.com/u/AbhishekMaheshwari123/", 
    "Shiven Rastogi" : "https://leetcode.com/u/Shiven_Rastogi/", 
    "Vaibhav Yadav" : "https://leetcode.com/u/money48_57/", 
    "Krishankant Saraswat" : "https://leetcode.com/u/krishankant_2003/", 
    "Siddhi Agarwal" : "https://leetcode.com/u/siddhiagarwalcs22/", 
    "Pranjal Raghuvanshi" : "https://leetcode.com/u/pranjal_r323/", 
    "mukul goyal" : "https://leetcode.com/u/Mukul_Goyal_2004/", 
    "Arpit Gupta" : "https://leetcode.com/u/Arpit0212/", 
    "Nikita Chaudhary" : "https://leetcode.com/u/0Nikki0/", 
    "Anoop Kumar" : "https://leetcode.com/u/The_Ghost_Coder/", 
    "Priyanshu Bhardwaj" : "https://leetcode.com/u/Priyanshu-Bhardwaj/", 
    "Archie Gupta" : "https://leetcode.com/u/Archie_Gupta/", 
    "Rahul Gangwar" : "https://leetcode.com/u/Rahul_Gangwar/", 
    "Khushi" : "https://leetcode.com/u/khushi_raghuvanshi19/", 
    "Prachi Agarwal" : "https://leetcode.com/u/prachiagarwal5/", 
    "Madhur mittal" : "https://leetcode.com/u/maddy30445r/", 
    "Tripti Gupta" : "https://leetcode.com/u/Tripti0911/", 
    "shivam gupta" : "https://leetcode.com/u/JlRg1FCYPt/", 
    "Satyam kumar singh" : "https://leetcode.com/u/satyam_kumar_singh/", 
    "Ayush Agrawal" : "https://leetcode.com/u/ayushagrawal-cs22/", 
    "Anshul Sharma" : "https://leetcode.com/u/anshul_pandit", 
    "Nikunj Gupta" : "leetcode.com/u/ngdec03", 
    "Akanksha" : "https://leetcode.com/u/akankshacs22/", 
    "ANUJ KUMAR" : "https://leetcode.com/u/anujjsengar/", 
    "Hemant Prajapati" : "https://leetcode.com/u/hemant1000/", 
    "Divyansh Singh" : "https://leetcode.com/u/Divyansh2304/", 
    "Sanskrati Agrawal" : "https://leetcode.com/u/agrawalsanskrati323/", 
    "Vidhi Ajmera" : "https://leetcode.com/u/Vidhi_Ajmera/", 
    "Shraddha Agrawal" : "https://leetcode.com/u/shraddhaa1/", 
    "Aadrika Jain" : "https://leetcode.com/u/Aadrika_Jain/", 
    "Anurag Pathak" : "https://leetcode.com/u/anuragpathak__/", 
    "Hema Dua" : "https://leetcode.com/u/Hema_dua/", 
    "SAURABH NAGAYACH" : "https://leetcode.com/u/saurabhnagaich27/", 
    "Dev Chikara" : "https://leetcode.com/u/devchikara05/", 
    "Harshit" : "https://leetcode.com/u/harshit_gla/", 
    "Krishna Agrawal" : "https://leetcode.com/u/krishnaagrawal_1/", 
    "Kartik Chahar" : "https://leetcode.com/u/Kartik_Chahar/", 
    "Dhruv Bansal" : "https://leetcode.com/u/dhruvbansal153/", 
    "Anshika Agarwal" : "https://leetcode.com/u/agarwalanshika74/", 
    "kushal sharma" : "https://leetcode.com/u/kushalsharma_1801/", 
    "Upendra Singh" : "https://leetcode.com/u/upendrasingh63/", 
    "Anjali Rawat" : "https://leetcode.com/u/AnjaliRawatAR/", 
    "Deepak shukla" : "https://leetcode.com/u/deepshukla1209/", 
    "Deepak Yadav" : "https://leetcode.com/u/dy5055290/", 
    "Krishna Gopal Sharma" : "https://leetcode.com/u/krishna-899/", 
    "Lucky Goyal" : "https://leetcode.com/u/Lucky_Goyal/", 
    "hemant vishu" : "https://leetcode.com/u/hemantvishu14/", 
    "Bhuvnesh Singh" : "https://leetcode.com/u/bhuvisingh_123/", 
    "Prerit Jain" : "https://leetcode.com/u/Prerit_jain05/", 
    "Amitabh Singh" : "https://leetcode.com/u/amitabhsingh128/", 
    "Shobhit Chaturvedi" : "https://leetcode.com/u/Shobhit1416/", 
    "Lakshya Khandelwal" : "https://leetcode.com/u/lakshyak1805/", 
    "Saksham yadav" : "https://leetcode.com/u/saksham_yadav09/", 
    "Divyanshu Rajoria" : "https://leetcode.com/u/Divyanshu0123", 
    "HEMANT KUMAR" : "https://leetcode.com/u/hemant_458/", 
    "DEVANSHU" : "Https://leetcode.com/u/devanshu_pathak/", 
    "Garvit Saraswat" : "https://leetcode.com/u/garvit1000/", 
    "Ananya Shukla" : "https://leetcode.com/u/user6540cY/", 
    "shailendra kumar yadav" : "https://leetcode.com/u/shortss124/", 
    "Vaibhavi Varshney" : "https://leetcode.com/u/vaibhavi_01/", 
    "Sanchit Agrawal" : "https://leetcode.com/u/sanxxit/", 
    "Dev Sisodiya" : "https://leetcode.com/u/Dev_Sisodiya/", 
    "Abhinav Yadav" : "https://leetcode.com/u/abhinav-yadav-16/", 
    "Ganesh kumar singh" : "https://leetcode.com/u/Ganesh_kumar_123/", 
    "Ansh Kapoor" : "https://leetcode.com/u/ansh75334/", 
    "Pritam Kumar Singh" : "https://leetcode.com/u/pritam_singh3201/", 
    "Sparsh Goyal" : "https://leetcode.com/u/Sparsh_Goyal/", 
    "Vikky kushwah" : "https://leetcode.com/u/mrvikky_17/", 
    "arjun suwedi" : "https://leetcode.com/u/KAAL_KIN/", 
    "Suyash Tripathi" : "https://leetcode.com/u/suyashtripathi333/", 
    "ANURAG SHARMA" : "https://leetcode.com/u/anurag080205/", 
    "Sandesh Yadav" : "https://leetcode.com/u/sandesh_yadav_cse2026/", 
    "Aditya Yadav" : "https://leetcode.com/u/aditya610/", 
    "Shyam Rai" : "https://leetcode.com/u/shyam_rai22/", 
    "Sambhav Tiwari" : "https://leetcode.com/u/sambhavtiwari/", 
    "Prince Bazad" : "https://leetcode.com/u/prince_bazad/", 
    "Ansh kapoor" : "https://leetcode.com/u/ansh75334/", 
    "Shreyanshi garg" : "https://leetcode.com/u/shreyanshigarg/", 
    "Animesh Gautam" : "https://leetcode.com/u/animeshgautam20/", 
    "Vansh Tyagi" : "https://leetcode.com/u/Vansh-Tyagi/", 
    "Sachin Kumar" : "https://leetcode.com/u/sachinthakurela2005/", 
    "sahil khandelwal" : "https://leetcode.com/u/sdesahil/", 
    "Rishabh tripathi" : "https://leetcode.com/u/rishtripathi998/", 
    "Akshay Garg" : "https://leetcode.com/u/akshay368/", 
    "Ayush Gupta" : "https://leetcode.com/u/guptaayush2005/", 
    "Yash Sharma" : "https://leetcode.com/u/YashSharma3/", 
    "Himanshu Mishra" : "https://leetcode.com/u/Ansh0007/", 
    "shubh sharma" : "https://leetcode.com/u/shubhsharma2005/", 
    "Himanshu SIngh" : "https://leetcode.com/u/happy04/", 
    "Krishna Gopal sharma" : "https://leetcode.com/u/krishna-899/", 
    "Satvik Gupta" : "https://leetcode.com/u/satvikg21111124/", 
    "Mradul Sharma" : "https://leetcode.com/u/Mradul2K04/", 
    "chitransh bharadwaj" : "https://leetcode.com/u/Chitransh00052/", 
    "Spriha Singh" : "https://leetcode.com/u/Spriha_Bhriguvanshi/", 
    "Bhuvnesh Kumar" : "https://leetcode.com/u/bhuvnesh-kumar/", 
    "Bhuvnesh kumar" : "https://leetcode.com/u/bhuvnesh-kumar/", 
    "Jayant sharma" : "https://leetcode.com/u/user6053jQ/", 
    "Tejpratap Singh" : "https://leetcode.com/u/2115500154/", 
    "Priyanshu Dubey" : "https://leetcode.com/u/Priyanshu_Dubey369", 
    "ANMOL AGARWAL" : "https://leetcode.com/u/HHhf22QzcY/", 
    "Lalit Kumar" : "https://leetcode.com/u/Lalit_chaudhary01/", 
    "Karan Agarwal" : "https://leetcode.com/u/karanagarwal003/",
     
    "Garv sharma" : "https://leetcode.com/u/user5744mj/", 
    "Ritik Tripathi" : "https://leetcode.com/u/Ritik_tripathi52/", 
    "Abhinav raj singh" : "https://leetcode.com/u/Abhinavrajsingh/", 
    "uday singh kushwaaha" : "https://leetcode.com/u/udaykushwaha/", 
    "Tanuj Mittal" : "https://leetcode.com/u/tanujmittal/", 
    "prashant chauhan" : "https://leetcode.com/u/prashantchauhan123/", 
    "Anushka Chaudhary" : "https://leetcode.com/u/Anushka_Chaudhary07/", 
    "Isha Chaudhary" : "https://leetcode.com/u/ishu_chaudhary/", 
    "Daman Pratap Singh" : "https://leetcode.com/u/Daman_07/", 
    "Manmohan Singh" : "https://leetcode.com/u/thakur_manmohan_singh/", 
    "Harsh Rajoria" : "https://leetcode.com/u/rajoriaharsh0/", 
    "Akshat Bansal" : "https://leetcode.com/u/Akshatbansal_12/", 
    "Divyanshu Khandagre" : "https://leetcode.com/u/divyanshu1604/", 
    "Devanshu Yadav" : "https://leetcode.com/u/devanshuyadav_/", 
    "Yatharth Dixit" : "https://leetcode.com/u/yatharth_dixit0097/", 
    "SARTHAK CHAHAR" : "https://leetcode.com/u/KsyeLjhSaH/", 
    "Aditi Singh" : "https://leetcode.com/u/Trustedfate/", 
    "Tushar Dixit" : "https://leetcode.com/u/tushardixit_6395/", 
    "Priyanshu Mangla" : "https://leetcode.com/u/priyanshu_mangla/", 
    "Satyam Vinayak" : "https://leetcode.com/u/satyamvinayak/", 
    "sachin raghav" : "https://leetcode.com/u/Sachin_raghav28/", 
    "Harsh Raj" : "https://leetcode.com/u/Harsh_raj_9973/", 
    "Mayank Dagar" : "https://leetcode.com/u/mayank_dagar666/", 
    "Saksham Saxena" : "https://leetcode.com/u/saxenasaksham09/", 
    "Rishabh Baghel" : "https://leetcode.com/u/Rishu_689/", 
    "Agrim Pradhan" : "https://leetcode.com/u/Agrim_Pradhan/", 
    "vivek kumar sharma" : "https://leetcode.com/u/gracefulvivektdl/", 
    "sheelesh  mishra" : "https://leetcode.com/u/Sheelesh_mishra2004/", 
    "Daksh Gaur" : "https://leetcode.com/u/alphamethamine/", 
    "Anant Tiwari" : "https://leetcode.com/u/anant19161704/", 
    "Shivam Singh" : "https://leetcode.com/u/SinghShivam007/", 
    "Arvind singh" : "https://leetcode.com/u/arvind_13/", 
    "Vivek Sisodiya" : "https://leetcode.com/u/Vivek_Sisodiya/", 
    "uday singh kushwaha" : "https://leetcode.com/u/udaykushwaha/", 
    "Atul Kumar" : "https://leetcode.com/u/atulmtr01542/", 
    "ritik upadhyay" : "https://leetcode.com/u/ritikupdy/", 
    "vivek pratap singh" : "https://leetcode.com/u/P5V1V3K/", 
    "Samiksha Chauhan" : "https://leetcode.com/u/_SAMIKSHA/", 
    "Vibhu Pratap" : "https://leetcode.com/u/VIBHUp151/", 
    "Puneet sharma" : "https://leetcode.com/u/puneetsharma9651/", 
    "Adarsh Verma" : "https://leetcode.com/u/AdarshV007/", 
    "Bhanu Pratap Singh" : "https://leetcode.com/u/bhanupratap_45/", 
    "Madhusudan Singh Chauhan" : "https://leetcode.com/u/madhusudan_chauhan/", 
    "Devansh Agrawal" : "https://leetcode.com/u/devansh_511/", 
    "Aryan Maheshwari" : "https://leetcode.com/u/AryanMaheshwari70/", 
    "Sachin Gola" : "https://leetcode.com/u/SachinGola200/", 
    "Piyush Agrawal" : "https://leetcode.com/u/Piyushagrawal95/", 
    "Kavya Agrawal" : "https://leetcode.com/u/kavya_ag12345/", 
    "Nikhil Bansal" : "https://leetcode.com/u/Nik26sal/", 
    "Aditya Patel" : "https://leetcode.com/u/12ArpitPatel/", 
    "Aman Kumar" : "https://leetcode.com/u/_Aman_Kumar/", 
    "Chetan Kumar" : "https://leetcode.com/u/Chetankumar191/", 
    "subhankar sau" : "https://leetcode.com/u/phoenix_ss/", 
    "sonam sharma" : "https://leetcode.com/u/sonam_sharma7088/", 
    "Raunak Mishra" : "https://leetcode.com/u/raunakmishra_/", 
    "Ishika Goyal" : "https://leetcode.com/u/goyal_ishika/", 
    "Abhi Gupta" : "https://leetcode.com/u/abhigupta1540/", 
    "Prasoon Sahay" : "https://leetcode.com/u/nZVOTxrUia/", 
    "Akash Yadav" : "https://leetcode.com/u/lifegod/", 
    "Apurva Gupta" : "https://leetcode.com/u/apurvag0108/", 
    "Kapil Gupta" : "https://leetcode.com/u/kg666235/", 
    "Vipul Kumar Yadav" : "https://leetcode.com/u/Vipul_cs22/", 
    "Aditi Mittal" : "leetcode.com/u/aditimittal04/", 
    "Palak Katara" : "https://leetcode.com/u/palakkatara/", 
    "Aryan Yadav" : "https://leetcode.com/u/aryanyadav_13/", 
    "Deepak Singh" : "https://leetcode.com/u/as8825598/", 
    "Shivam Rai" : "https://leetcode.com/u/ShivamRai2003/", 
    "Nishant Pathak" : "https://leetcode.com/u/Nishant_1_8/", 
    "Piyush Gupta" : "https://leetcode.com/u/PIYUSH-0612/", 
    "Deepali Bisht" : "https://leetcode.com/u/deepali_2223/", 
    "Aman Verma" : "https://leetcode.com/u/avaman7860/", 
    "Medini Joshi" : "https://leetcode.com/u/MediniJoshi/", 
    "Govind N Acharya" : "https://leetcode.com/u/Govind_Acharya/", 
    "Vishwajeet Singh" : "https://leetcode.com/u/vishwajeet7872/", 
    "Ritik gupta" : "https://leetcode.com/u/ritik0936/", 
    "Nitai Gupta" : "https://leetcode.com/u/nitaigupta2003/", 
    "Anjali Varshney" : "https://leetcode.com/u/anjalivarshney02/", 
    "Yash kumar kasaudhan" : "https://leetcode.com/u/vididvidid/", 
    "AYUSH GUPTA" : "https://leetcode.com/u/ayush456/", 
    "Abhishek Sharma" : "https://leetcode.com/u/2215000061_ABHISHEK/", 
    "Kanhaiya Garg" : "https://leetcode.com/u/kingDAS/", 
     
    "Bhumika Chaudhary" : "https://leetcode.com/u/Bhumika_2004/", 
    "Saloni Kumari" : "https://leetcode.com/u/Saloni_kumari3/", 
    "Naina Sharma" : "https://leetcode.com/u/naina_sharma/", 
    "Manya Sharma" : "https://leetcode.com/u/manya_298/", 
    "Sarthak Shishodia" : "https://leetcode.com/u/Sarthak_Shishodia20/", 
    "Kartikay Garg" : "https://leetcode.com/u/Kartikay-Garg18/", 
    "Nyasa Sharma" : "https://leetcode.com/u/Nyasa_sharma/", 
    "Vipul Duve" : "https://leetcode.com/u/Vipul_Duve/", 
    "Gourang Gautam" : "https://leetcode.com/u/Gourang_05/", 
    "Nitin Kumar Sharma" : "https://leetcode.com/u/Nitinsharma76/", 
    "Rudrika Raghav" : "https://leetcode.com/u/rudrika_2425/", 
    "Mohit Sharma" : "https://leetcode.com/u/Mohitsharma3817/", 
    "Vaishnavi Sharma" : "https://leetcode.com/u/sharma_vaishnaviii/", 
    "Shivam Kumar" : "https://leetcode.com/u/shivam25kumar04/", 
    "Rishabh Gupta" : "https://leetcode.com/u/rishabhgupta1_cs22/", 
    "Divyansh Goyal" : "https://leetcode.com/u/neerajdivyanshruchi1/", 
    "Anushka Mishra" : "https://leetcode.com/u/anushkamishra2309/", 
    "Rahul Lodhi" : "https://leetcode.com/u/Rahullodhi900/", 
    "Vivek Singh" : "https://leetcode.com/u/Kavi_Singh/", 
    "Chirag Chauhan" : "https://leetcode.com/u/user7155Ud/", 
    "Divyansh Yadav" : "https://leetcode.com/u/Divyansh20004/", 
    "Chetna" : "https://leetcode.com/u/gargchetna11/", 
    "Aditya Khare" : "https://leetcode.com/u/Aditya_Khare18/", 
    "Saksham Kumar" : "https://leetcode.com/u/saksham_kumar565/", 
    "Madhav Goyal" : "https://leetcode.com/u/madhavgoyal012/", 
    "Vaibhav Varshney" : "https://leetcode.com/u/Vaibhav_0415/", 
    "Pulkit upadhyay" : "https://leetcode.com/u/_22215001361/", 
    "Ankush Tyagi" : "https://leetcode.com/u/ankushtyagi02/", 
    "Utkarsh Agarwal" : "https://leetcode.com/u/utkarsh_agar/", 
    "Shreya Omer" : "https://leetcode.com/u/shreyaomer657/", 
    "Arjun Singh" : "leetcode.com/u/arjun4444/", 
    "Hemant Kaushik" : "https://leetcode.com/u/hemantach/", 
    "Srishti Gupta" : "https://leetcode.com/u/srishti_017/", 
    "Surya Pratap Singh" : "https://leetcode.com/u/suryasingh337/", 
    "Farkansh Gupta" : "https://leetcode.com/u/farkansh_gupta/", 
    "Kailash Nath Yadav" : "https://leetcode.com/u/Kailash7781/", 
    "Gayatri Chaudhary" : "https://leetcode.com/u/gayatri_cs-22/", 
    "Ankit Chaudhary" : "https://leetcode.com/u/Ankit_chaudhary_/", 
    "preksha gupta" : "https://leetcode.com/u/prekshag460/", 
    "Divyanshi Gupta" : "https://leetcode.com/u/divyanshi_50/", 
    "Palak Sandil" : "https://leetcode.com/u/Palak_Sharma100/", 
    "Aditya Narayan Gupta" : "https://leetcode.com/u/AdityaNarayanGupta_2004/", 
    "MADHAV SHARMA" : "https://leetcode.com/u/Madhav_Sharma_07/", 
    "Zainab Parveen" : "https://leetcode.com/u/zainab098/", 
    "Prateek Singh Yashwardhan" : "https://leetcode.com/u/prateeksinghyashwardhan_cs22/", 
    "Kartik Varshney" : "https://leetcode.com/u/user1038PX/", 
    "kuldeep sharma" : "https://leetcode.com/u/Kuldeepsharma5836/", 
    "Satyam Karn" : "https://leetcode.com/u/Karnsaty/", 
    "Hardik Mishra" : "https://leetcode.com/u/hardikmishra20040925/", 
    "Atul Gupta" : "https://leetcode.com/u/spectre007_atul/", 
    "Anay Gupta" : "https://leetcode.com/u/Anay_Gupta45/", 
    "Shubhang Sharma" : "https://leetcode.com/u/ShubhangSharma_30/", 
    "KSHITIZ JAIN" : "https://leetcode.com/u/kshitiz001/", 
    "Anubhav Deep Srivastav" : "https://leetcode.com/u/Anubhavdeepsrivastav/", 
    "Shubhneet Kaur" : "https://leetcode.com/u/kaur_shubh/", 
    "Radhika Agarwal" : "https://leetcode.com/u/Radhika_Agarwal22/", 
    "Priyanshi yadav" : "https://leetcode.com/u/Priyanshi1883/", 
    "khushi kumari" : "https://leetcode.com/u/_khushii/", 
    "Aditi Varshney" : "https://leetcode.com/u/aditi34/", 
    "Dhruv Goyal" : "https://leetcode.com/u/Dhruv06/", 
    "Harsh Bansal" : "https://leetcode.com/u/harshbansal695/", 
    "Abhishek kumar" : "https://leetcode.com/u/Abhishek3230/", 
    "Amar Varshney" : "https://leetcode.com/u/Amarvarshney03/", 
    "GAURAV VERMA" : "https://leetcode.com/u/CodeGaur/", 
    "Shiva Gaur" : "https://leetcode.com/u/shivagaur1100/", 
    "Pushpak Singhal" : "https://leetcode.com/u/Pushpak_Coder/", 
    "Naman Agrawal" : "https://leetcode.com/u/naman_starcoder/", 
    "Prashant Pathak" : "https://leetcode.com/u/prashantpathak01/", 
    "Harsh Pathak" : "https://leetcode.com/u/Harsh-1808/", 
    "Bhanu dagur" : "https://leetcode.com/u/bhanu_24/", 
    "Krishna Sharma" : "https://leetcode.com/u/Dante_0007/", 
    "Sameer Kushwaha" : "https://leetcode.com/u/s_a_m2003/", 
    "Mahesh Pandey" : "https://leetcode.com/u/Mahesh_pandey/", 
    "Dheeraj vashishtha" : "https://leetcode.com/u/Dheeru_vashishtha/", 
    "Dipanshu Kumar" : "https://leetcode.com/u/Dipanshu_Kumar1/", 
    "Pankaj Pandey" : "https://leetcode.com/u/pankajpandey9351/", 
    "Satyam Kumar" : "https://leetcode.com/u/i_m_sks12", 
    "Priyanshu Sharma" : "https://leetcode.com/u/Priyanshucs22/", 
    "Dheeraj vaashishtha" : "https://leetcode.com/u/Dheeru_vashishtha/", 
    "Dheeraj Kriplani" : "https://leetcode.com/u/Dheeraj_2602/", 
    "Ashutosh Singh Chauhan" : "https://leetcode.com/u/Ashutosh-chauhan_29/", 
    "Dhruv sahu" : "https://leetcode.com/u/dhruvsahu/", 
    "Aastha Jaiswal" : "https://leetcode.com/u/aastha-2002/", 
    "Bhakti Chaudhary" : "https://leetcode.com/u/bhakti11/", 
    "Anshita Agrawal" : "https://leetcode.com/u/Anshita_Agrawal/", 
    "Abhishek Pandey" : "https://leetcode.com/u/_abhishekpandey__/", 
    "Satyam Gupta" : "https://leetcode.com/u/Neofighter1/", 
    "Komal Faujdaar" : "https://leetcode.com/u/komal_04/", 
    "Vidhi Khandelwal" : "https://leetcode.com/u/vidhi_1503/", 
    "Suraj Sharma" : "https://leetcode.com/u/surajsh4646/", 
    "shikha" : "https://leetcode.com/u/shikha_2/", 
    "SHREYASH SINGH" : "https://leetcode.com/u/shreyash_singh123/", 
    "Khushi Rathore" : "https://leetcode.com/u/Khushi1_Rathore/", 
    "Devansh Singh" : "https://leetcode.com/u/devansh_singh1001/", 
    "Ankit singh" : "https://leetcode.com/u/ANKITSINGHD10S/", 
    "Nipun Rajput" : "https://leetcode.com/u/NipunRajput0312/", 
    "Rohit Kumar" : "https://leetcode.com/u/Rohit_kumar_45/", 
    "Anuj Chaturvedi" : "https://leetcode.com/u/Anujchaturvedi/", 
    "Tushar Sharma" : "https://leetcode.com/u/Tushar0sharmA/", 
    "Devanshi Lawania" : "https://leetcode.com/u/Devanshi_Lawania_123/", 
    "Harshul Sengar" : "https://leetcode.com/u/HARSHUL_SENGAR/", 
    "Alankrati Saxena" : "https://leetcode.com/u/Alan_Krati/", 
    "DEVIKA AGARWAL" : "https://leetcode.com/u/devikaagarwal83/", 
    "Shivang Shukla" : "https://leetcode.com/u/shivangshukla201/", 
    "Sankalp Agarwal" : "https://leetcode.com/u/Sankalp_Agarwal_18/", 
    "Gauri Agrawal" : "https://leetcode.com/u/Gauri__Agrawal/", 
    "Sumit Kumar" : "https://leetcode.com/u/Sumitkg1/", 
    "Tanya Maheshwari" : "https://leetcode.com/u/tanya50/", 
    "Garvit Gaur" : "https://leetcode.com/u/garvitgaur/", 
    "Gaurav kumar" : "https://leetcode.com/u/gauravkumar781902/", 
    "Arihant Jain" : "https://leetcode.com/u/Arihant77777/", 
    "Alpana Rawat" : "https://leetcode.com/u/Alpana594/", 
    "Sparsh Ranjan" : "https://leetcode.com/u/ranjansparsh872/", 
    "Milan Awasthi" : "https://leetcode.com/u/Milanawasthi/", 
    "Sajal Singh" : "https://leetcode.com/u/user9189p/", 
    "Harshita Das" : "https://leetcode.com/u/2005harshu/", 
    "Pari Upadhyay" : "https://leetcode.com/u/pari63/", 
    "Devansh Agarwal" : "https://leetcode.com/u/devanshagarwal0/", 
    "Mohd Asad Ansari" : "https://leetcode.com/u/Ninja_ansari/", 
    "Anik Garg" : "https://leetcode.com/u/ANIK_GARG/", 
    "Akanksha Shakya" : "https://leetcode.com/u/Akanksha_016/", 
    "Deepali Yadav" : "https://leetcode.com/u/deepali_yadav_cs22/", 
    "SAMARTH PRAKASH SHAKYA" : "https://leetcode.com/u/SAMARTH-SHAKYA/", 
    "Dileep Kumar Mishra" : "https://leetcode.com/u/Sting_Coder/", 
    "Khushi Goyal" : "https://leetcode.com/u/khushi_goyal__/", 
    "Arjun Raghav" : "https://leetcode.com/u/arjunraghav/", 
    "Himanshu Prakash Mishra" : "https://leetcode.com/u/himanshumishra8907/", 
    "Atishay Garg" : "https://leetcode.com/u/atishaygarg11/", 
    "Khushi Rathi" : "https://leetcode.com/u/khushi_084/", 
    "Anubhav Yadav" : "https://leetcode.com/u/anubhav32/", 
    "ARIHANT JAIN" : "https://leetcode.com/u/Arihant77777/", 
    "Anshika Tripathi" : "https://leetcode.com/u/Anshika_Tripathi_12/", 
    "Abhinav Tomar" : "https://leetcode.com/u/Tomar_Abhinav/", 
    "shreyansh shrivastava" : "https://leetcode.com/u/shreyansh_shri/", 
    "tanu" : "https://leetcode.com/u/user2440Lp/", 
    "Ayush" : "https://leetcode.com/u/aayushsingh7668/", 
    "Divya Prakash Singh" : "https://leetcode.com/u/kashanra7/", 
    "Ayush Garg" : "https://leetcode.com/u/ayushgarg9986/", 
    "Abhay Somani" : "https://leetcode.com/u/abhay_somani/", 
    "Dinesh" : "https://leetcode.com/u/Dinesh_sirsiya75/", 
    "Uttam Kumar" : "https://leetcode.com/u/uttam_roy01/", 
    "ALPANA" : "https://leetcode.com/u/Alpana594/", 
    "Narendra singh" : "https://leetcode.com/u/narendrasingh1718/", 
    "Prashant Chaudhary" : "https://leetcode.com/u/Prashant_Chaudhary_/", 
    "Anurag" : "https://leetcode.com/u/Anurag051104/", 
    "Himanshu raghav" : "https://leetcode.com/u/himanshud310/", 
    "Bhaskar Gautam" : "https://leetcode.com/u/BhaskarGautam24/", 
    "Chirag Agarwal" : "https://leetcode.com/u/chiragagarwal2695/", 
    "Bhuvnesh Sharma" : "https://leetcode.com/u/bhuvnesharma/", 
    "Bharat Agrawal" : "https://leetcode.com/u/bharat_ajirawal/", 
    "Pushpendra Upadhyay" : "https://leetcode.com/u/Pushpendra_Upadhyay02/", 
    "Rahul Jadon" : "https://leetcode.com/u/Rahul_Jadon/", 
    "Vaidehi khandelwal" : "https://leetcode.com/u/Vaidehi_108/", 
    "Rajat Chaudhary" : "https://leetcode.com/u/Rjch18/", 
    "Naveen Gaur" : "https://leetcode.com/u/naveengaur24/", 
    "Himanshu Tiwari" : "https://leetcode.com/u/himanshutiwari1063/", 
    "Prashant jadon" : "https://leetcode.com/u/prashantthakur_4111/", 
    "devika agarwal" : "https://leetcode.com/u/devikaagarwal83/", 
    "Deepika Rawat" : "https://leetcode.com/u/deepikarawat_cs22/", 
    "Anurag Gautam" : "https://leetcode.com/u/AnuragGautam02/", 
    "Arun Kumar" : "https://leetcode.com/u/arunkumar56/", 
    "Tej Prakash Singh" : "https://leetcode.com/u/Tej_prakash_singh/", 
    "Kartik Arora" : "https://leetcode.com/u/Kartik_04/", 
    "Rahul" : "https://leetcode.com/u/Rahul_1384/", 
    "Anukalp Raj" : "https://leetcode.com/u/singhanukalp/", 
    "Deepanjali Singh" : "https://leetcode.com/u/deepanjalisingh/", 
    "Shruti Chauhan" : "https://leetcode.com/u/shrutichauhan007/", 
    "Narayan" : "https://leetcode.com/u/narayanthakur7348/", 
    "Pushpendra" : "https://leetcode.com/u/Pushpendra07/", 
    "Kushal yadav" : "https://leetcode.com/u/kushal_589/", 
    "Jatin Kumar Singh" : "https://leetcode.com/u/jatinthakur2817/", 
    "Utkarsh Sharma" : "https://leetcode.com/u/Utkarsh_Sharma_01/", 
    "Archit jain" : "https://leetcode.com/u/archit2709/", 
    "Sravan kumar" : "https://leetcode.com/u/3-shravan/", 
    "Soumya Kumar Gupta" : "https://leetcode.com/u/soumya_kumar_gupta/", 
    "Nitish Kumar" : "https://leetcode.com/u/fgrreloaded/", 
    "Navam Srivastava" : "https://leetcode.com/u/navam18/", 
    "Aryan Verma" : "https://leetcode.com/u/aryanverma26/", 
    "Akshay Kumar" : "https://leetcode.com/u/akshay_ydv07/", 
    "Naman Mishra" : "https://leetcode.com/u/i_namanmishra/", 
    "Navya Yadav" : "https://leetcode.com/u/Navyaa_24/", 
    "Sakshi Singh" : "https://leetcode.com/u/sakshisingh_2910/", 
    "TANISH GUPTA" : "https://leetcode.com/u/tanish-hrk/", 
    "Shriyesh Dixit" : "https://leetcode.com/u/d_shriyesh/", 
    "Shreeya Gupta" : "https://leetcode.com/u/shreeyagupta6342/", 
    "Raj Gupta" : "https://leetcode.com/u/rajgupta_19/", 
    "Khushi Tiwari" : "https://leetcode.com/u/Tiwari_Khushi/", 
    "Aryan Malik" : "https://leetcode.com/u/aryan_code03/", 
    "Srijan Mani Tripathi" : "https://leetcode.com/u/srijan122/", 
    "krishna punj singh" : "https://leetcode.com/u/krishna143143/", 
    "Yash Singhal" : "https://leetcode.com/u/rcbcoder/", 
    "Raj Srivastava" : "https://leetcode.com/u/Raj_Srivastava20505/", 
    "Divyansh Bhatt" : "https://leetcode.com/u/divyansh_b11/", 
    "Sameer Tomar" : "https://leetcode.com/u/Sameer_1_/", 
    "Manya Arjariya" : "https://leetcode.com/u/Manya_77/", 
    "Pranjal Verma" : "https://leetcode.com/u/PranjalVerma_01/", 
    "Akash sharma" : "https://leetcode.com/u/AkashS20/", 
    "Shubh Sonakiya" : "https://leetcode.com/u/Shubh_Sonakiya/", 
    "Pushp sharma" : "https://leetcode.com/u/pushp_sharmaa/", 
    "Rishabh singh" : "https://leetcode.com/u/Rishabh_singhcs22/", 
    "SAMYAK JAIN" : "https://leetcode.com/u/SamyakJain08/", 
    "SHUBH VARSHNEY" : "https://leetcode.com/u/shubh0104/", 
    "Vansh sharma" : "https://leetcode.com/u/vansh_sh970/", 
    "Shashi Kumar Yadav" : "https://leetcode.com/u/skyy4/", 
    "Arushi Garg" : "https://leetcode.com/u/Arushi_21/", 
    "Kartik Saha" : "https://leetcode.com/u/sahakartik2952004/", 
    "Akarsh Khandelwal" : "https://leetcode.com/u/Akarshkh/", 
    "Kush Varshney" : "https://leetcode.com/u/user4079yp/", 
    "Abhinendra Singh" : "https://leetcode.com/u/abhinendrasingh/", 
    "Vansh Singhal" : "https://leetcode.com/u/vansh_singhal007/", 
    "Shivam  Pratap Singh" : "https://leetcode.com/u/shivampratapsingh181/", 
    "Himanshi Agrawal" : "https://leetcode.com/u/himan_shi/", 
    "Prakhar Kapoor" : "https://leetcode.com/u/prakharkapoorcollege/", 
    "Atharva Jaiswal" : "https://leetcode.com/u/itsaj01/", 
    "Khushi Varshney" : "https://leetcode.com/u/VarshneyKhushi/", 
    "Mayank Sharma" : "https://leetcode.com/u/mayanksharma12662/", 
    "sonu" : "https://leetcode.com/u/SonuSingh7869/", 
    "Lovekush Rajput" : "https://leetcode.com/u/LOVEKUSH_RAJPUT/", 
    "Deepak Dubey" : "https://leetcode.com/u/Deepak-Dubey-cs/", 
    "Chaman Faujdar" : "https://leetcode.com/u/Chaman_faujdar/", 
    "Pratham" : "https://leetcode.com/u/PrathamCoder01/", 
    "Lokesh Kumar" : "https://leetcode.com/u/lokesh2910/", 
    "Akshit Kumar" : "https://leetcode.com/u/akshit_100/", 
    "Manish Pailwar" : "https://leetcode.com/u/ManishPailwar/", 
    "Nived Agrawal" : "https://leetcode.com/u/Nived_agrawal/", 
    "Raj Bahadur Singh" : "https://leetcode.com/u/Rajbsingh/", 
    "Ritesh Kumar" : "https://leetcode.com/u/thisismeriteshk1/", 
    "Sakshi Maholiya" : "https://leetcode.com/u/sakshi_Maholiya/", 
    "Celina Sharma" : "https://leetcode.com/u/celina_sharma03/", 
    "Ashish Kumar Verma" : "https://leetcode.com/u/Ashish_Kumar_Verma/", 
    "Komal Gupta" : "https://leetcode.com/u/komalgupta8/", 
    "Kunal Varshney" : "https://leetcode.com/u/kunalvarshney/", 
    "Khushboo Agrawal" : "https://leetcode.com/u/khushiag565/", 
    "Rohit Rawat" : "https://leetcode.com/u/rohit2348834/", 
    "MANISH KUMAR" : "https://leetcode.com/u/user6786ic/", 
    "Saksham Agrawal" : "https://leetcode.com/u/Saksham_agrawal/", 
    "Mukul Kumar" : "https://leetcode.com/u/_Mukul_Dev_/", 
    "Kavya Jaimini" : "https://leetcode.com/u/ikavya_05/", 
    "Gaurav Chaudhary" : "https://leetcode.com/u/Gaurav__Chaudhary/", 
    "Ayush Alapuriya" : "https://leetcode.com/u/its_alapuriya/", 
    "Tanisha Singh" : "https://leetcode.com/u/Tanisha_016/", 
    "AKASH KUMAR" : "https://leetcode.com/u/AKASH-DEV-23/", 
    "Nainshi Verma" : "https://leetcode.com/u/nainshiverma2005/", 
    "Kalpit Chaudhary" : "https://leetcode.com/u/kalpit_chaudhary_cs/", 
    "Jyoti Upadhyay" : "leetcode.com/u/Jyoti-2215000856", 
    "Shivangi Trivedi" : "https://leetcode.com/u/shivangitrivedi/", 
    "gagan kumar" : "https://leetcode.com/u/gagan_654/", 
    "Madhu Solanki" : "https://leetcode.com/u/madhusolanki/", 
    "Himanshi Goyal" : "https://leetcode.com/u/Himanshigoyal_34/", 
    "Mahima Mishra" : "https://leetcode.com/u/mahi0203/", 
    "Anuj kumar" : "https://leetcode.com/u/AXg0B2cViR/", 
    "Harshit Chaudhary" : "https://leetcode.com/u/Harshit_Chaudhary8/", 
    "Ansh Sharma" : "https://leetcode.com/u/ansh_sharma_cs22/", 
    "Durgesh Bahadur Singh" : "https://leetcode.com/u/Durgesh_Bahadur/", 
    "Luvya sharma" : "https://leetcode.com/u/LuvyaSharma/", 
    "NIPUN AGRAWAL" : "https://leetcode.com/u/nipun_30/", 
    "Harshit barua" : "https://leetcode.com/u/studyharshit21/", 
    "Radhika Mittal" : "https://leetcode.com/u/Radhika_Mittal_516/", 
    "Priyank Singh" : "https://leetcode.com/u/priyanksingh_001/", 
    "Yash Dwivedi" : "https://leetcode.com/u/Unknown69/", 
    "Gaurav Mangal" : "https://leetcode.com/u/gauravman96/", 
    "Sagar Sharma" : "https://leetcode.com/u/SagarSharma252004/", 
    "Prashant Singh" : "https://leetcode.com/u/Prashant_Singh_001/", 
    "Ayushi Narayan" : "https://leetcode.com/u/AXr9rh3DzH/", 
    "Ankit Sahu" : "leetcode.com/u/ankit6387/", 
    "Vaishali Agrawal" : "https://leetcode.com/u/vaishali_1819/", 
    "Poonam Saraswat" : "https://leetcode.com/u/poonamsaraswat3105/", 
    "Sachin" : "https://leetcode.com/u/Sachin32455/", 
    "ayush" : "https://leetcode.com/u/ayushrawat200511/", 
    "Kartikeya Saxena" : "https://leetcode.com/u/kartikeyasaxen2601/", 
    "Aditya Pandey" : "https://leetcode.com/u/_pandeyad/", 
    "Abhishek Pathak" : "https://leetcode.com/u/abhipathak4546/", 
    "Yash Vishwakarma" : "https://leetcode.com/u/yashhvishwakarma/", 
    "Aagman Nag" : "https://leetcode.com/u/Aagmannag", 
    "Shashwat Dwivedi" : "https://leetcode.com/u/Shashwatdwivedi99/", 
    "Agraj Gaur" : "https://leetcode.com/u/user1456qi/", 
    "Dev Rishi Sharma" : "https://leetcode.com/u/Sdev76/", 
    "Aditya Gurjar" : "https://leetcode.com/u/aditya_gurjar_123/", 
    "himanshu" : "https://leetcode.com/u/Himanshu_Dhaked/", 
    "Aditey Rai" : "https://leetcode.com/u/Aditey19/", 
    "Vansh Mittal" : "https://leetcode.com/u/vansh_-0811/", 
    "saumy gupta" : "https://leetcode.com/u/saumy_gupta/", 
    "Sarthak Sinha" : "https://leetcode.com/u/Sarthak-Sinha/", 
    "Sarthak Patel" : "https://leetcode.com/u/sarthak_patel26/", 
    "Janhavi Singh" : "https://leetcode.com/u/janhavisingh_22/", 
    "Aryan Chaturvedi" : "https://leetcode.com/u/chaturvediaryan409/", 
    "Sneha Agrawal" : "https://leetcode.com/u/Sneha_Agrawal_07/", 
    "Nandini Solanki" : "https://leetcode.com/u/nandini_solanki8282/", 
    "Harshit Parmar" : "https://leetcode.com/u/harshit240205/", 
    "Dushyant Sharma" : "https://leetcode.com/u/dushyantsharma_18/", 
    "Manas Verma" : "https://leetcode.com/u/Manasverma369/", 
    "Pranjali Dixit" : "https://leetcode.com/u/8PyfVhh37A/", 
    "SHUBHANKIT BHARDWAJ" : "https://leetcode.com/u/bhardwajshubhankit8/", 
    "Piyush Rathor" : "https://leetcode.com/u/piyush_rathor/", 
    "nikhil singh" : "https://leetcode.com/u/its_nikhil01/", 
    "Priyanshi Gupta" : "https://leetcode.com/u/priyaanshayy/", 
    "Manish Chauhan" : "https://leetcode.com/u/manish_0001/", 
    "Shaivya singh" : "https://leetcode.com/u/2shaivya/", 
    "Shruti Gupta" : "https://leetcode.com/u/shrutigupta_22/", 
    "NIKHIL" : "https://leetcode.com/u/nikhilyadavji666/", 
    "Abhay pratap singh" : "https://leetcode.com/u/_rumpy_pumpy_/", 
    "Harsh Agrawal" : "https://leetcode.com/u/harsh_agrawal_/", 
    "Utkarsh Rajput" : "https://leetcode.com/u/Utkarsh_Rajput-/", 
    "Yash Ruhela" : "https://leetcode.com/u/yash_ruhela_73/", 
    "Yash Agrawal" : "https://leetcode.com/u/Yash_9548/", 
    "Akshay Singh" : "https://leetcode.com/u/akshay_singh_11/", 
    "Shruti Sharma" : "https://leetcode.com/u/shruti_sharma2901/", 
    "Rishika Pawaria" : "https://leetcode.com/u/Rishika_Pawaria/", 
    "Rahul Yaduvanshi" : "https://leetcode.com/u/rahul_rajput75/", 
    "Radhika Sharma" : "https://leetcode.com/u/Radhika_021/", 
    "Deepak Kumar Rajput" : "https://leetcode.com/u/deepak1688/", 
    "Sauhard kaushik" : "https://leetcode.com/u/sauhard_01/", 
    "ANIL SINGH" : "https://leetcode.com/u/Anil_Singh_Kuntal/", 
    "Sumit kumar verma" : "leetcode.com/u/Venom018/", 
    "Hrishabh durwar" : "https://leetcode.com/u/hrishabhcs22/", 
    "Subhash Singh" : "https://leetcode.com/u/Subhash_Singh/", 
    "2215000902" : "https://leetcode.com/u/kH-989_71/", 
    "Arun Chaudhary" : "https://leetcode.com/u/Arun_chaudhary01/", 
    "Vijay Kumar" : "https://leetcode.com/u/vijaykumarmganj1/", 
    "Abhay Giri" : "https://leetcode.com/u/AbhayGiri/", 
    "Harshika garg" : "https://leetcode.com/u/harshikaagrawal852/", 
    "RAJAT PATHAK" : "https://leetcode.com/u/RajatPathak31/", 
    "Shreyanshi Jain" : "https://leetcode.com/u/Shreyanshi_Jain/", 
    "Ayush Agnihotri" : "https://leetcode.com/u/Ayyush063/", 
    "Rohit choudhary" : "https://leetcode.com/u/Rohitchoudhary669/", 
    "Avnish" : "https://leetcode.com/u/Avnish1209/", 
    "Harshit Gargacharya" : "https://leetcode.com/u/Harshitcs22/", 
    "kanhaiya kasuhik" : "https://leetcode.com/u/kanhaiya-kaushik/", 
    "sumit kumar verma" : "https://leetcode.com/u/Venom018/", 
    "Sarvesh Mishra" : "https://leetcode.com/u/idsarvesh_/", 
    "TRISHI GAUR" : "https://leetcode.com/u/trishigaur/", 
    "Anmeha Pandey" : "https://leetcode.com/u/ANMEHAER/", 
    "Bhisam Kumar" : "https://leetcode.com/u/private_jaat/", 
    "Parth Gupta" : "https://leetcode.com/u/GuptaRth", 
    "Prakhar Gupta" : "https://leetcode.com/u/PrakharGupta77/", 
    "Rahul Gupta" : "https://leetcode.com/u/rahulgupta00/", 
    "vedatmika" : "https://leetcode.com/u/Vedatmika_shukla-18/",
    "Abhay Singh" : "https://leetcode.com/u/abhay_singh1209/", 
    "Bharat Dixit" : "https://leetcode.com/u/bharat010703", 
    "Aman Kumar Chaubey" : "https://leetcode.com/u/Amankumarchaubey2901/", 
    "Vishnu Upadhyay" : "https://leetcode.com/u/Vishnu_upadhyay/", 
    "Prakhar Srivastava" : "https://leetcode.com/u/prakharsrivast_cs22/", 
    "Bhavana Jadon" : "https://leetcode.com/u/sonaljadon254/", 
    "Priyanshu Yadav" : "https://leetcode.com/u/PriyanshuYadav9756/", 
    "Aditya Singh" : "https://leetcode.com/u/adityasingh-2004/", 
    "Lakshya DWivedi" : "https://leetcode.com/u/kamina_69/", 
    "Kshitiz Agarwal" : "https://leetcode.com/u/kshitiz_agarwal_/", 
    "Pranjal Goyal" : "https://leetcode.com/u/pranjal1082002/", 
    "Shivendra pandey" : "https://leetcode.com/u/shivendra_1511/", 
    "Jyotika Kishor" : "https://leetcode.com/u/Jyotika_k/", 
    "krishna sharma" : "https://leetcode.com/u/_krishna28_/", 
    "Shashank Srivastava" : "https://leetcode.com/u/shashanksrivastava/", 
    "siddharth" : "https://leetcode.com/u/siddharth__8701/", 
    "Amit Agarwal" : "https://leetcode.com/u/amit_ag87/", 
    "Avika Gupta" : "https://leetcode.com/u/Avika_31/", 
    "Rohit Singh" : "https://leetcode.com/u/ytrohit2004/", 
    "Rishit kesharwani" : "https://leetcode.com/u/Rishitkesharwani/", 
    "Ayush Mittal" : "https://leetcode.com/u/Ayush_6793/", 
    "Abhay Pratap Singh" : "https://leetcode.com/u/abhaypratap05ap/", 
    "Muskan Agrawal" : "https://leetcode.com/u/muskan_agrawal31/", 
    "Priyanshu sharma" : "https://leetcode.com/u/priyanshusharm1cs/", 
    "Ankit Pandey" : "https://leetcode.com/u/ankit_2215000255/", 
    "Muskan Gupta" : "https://leetcode.com/u/muskangupta200405/", 
    "Yatin Saraswat" : "https://leetcode.com/u/Yatin_saraswat/", 
    "Sakshi Yadav" : "https://leetcode.com/u/skshi1604/", 
    "Abhilasha" : "https://leetcode.com/u/Abhilasha_21/", 
    "Sagar Rajput" : "https://leetcode.com/u/sagarrajput1810/", 
    "Deepanshu Khandelwal" : "https://leetcode.com/u/Deepanshu-Khandelwal/", 
    "Ashvani Sharma" : "https://leetcode.com/u/ashvani8077/", 
    "Upendra sisodiya" : "https://leetcode.com/u/sirfupendra/", 
    "Kuldeep Singh" : "https://leetcode.com/u/KuldeepSingh7249/", 
    "Priyanshu Dhaked" : "https://leetcode.com/u/Priyanshu_dhaked/", 
    "Sachin Chaudhary" : "https://leetcode.com/u/sn9720477301/", 
    "Divyanshu kumar" : "https://leetcode.com/u/Divyanshu_kumar2279/", 
    "Kshitij Sahu" : "https://leetcode.com/u/kshitijsahucs22/", 
    "Abhishek Verma" : "https://leetcode.com/u/Abhishek__Verma/", 
    "Prinshi Singh" : "https://leetcode.com/u/prinshi_singh/", 
    "bhupender bhamla" : "https://leetcode.com/u/bhupender_bhamla/", 
    "Vishal Sisodiya" : "https://leetcode.com/u/Vishal_Sisodiya24/", 
    "Dipanshu Sharmq" : "https://leetcode.com/u/dipanshu_sharma194/", 
    "Vijay Singh" : "https://leetcode.com/u/vijaysingh-123/", 
    "Hritik Kumar" : "https://leetcode.com/u/Hritiksingh66/", 
    "Pratagya Garg" : "https://leetcode.com/u/pratagyagarg14/", 
    "ankit rawat" : "https://leetcode.com/u/rawatankit/", 
    "Pallavi Srivastava" : "https://leetcode.com/u/pallavi31/", 
    "Mohit Kumar Sharma" : "https://leetcode.com/u/montyrao/", 
    "Saurabh nagayach" : "https://leetcode.com/u/saurabhnagaich27/", 
    "Nikhil Dubey" : "https://leetcode.com/u/Niikhiil1/", 
    "Ayush Ponia" : "https://leetcode.com/u/Ayush_Ponia/", 
    "Ayushman Verma" : "https://leetcode.com/u/Ayushman_Verma9/", 
    "Deepali yadav" : "https://leetcode.com/u/deepali_yadav_cs22/", 
    "Samradh Srivastava" : "https://leetcode.com/u/Samradhsri/", 
    "Aryahans Bhati" : "https://leetcode.com/u/SMLhck3BVM/", 
    "Ananya Singh" : "https://leetcode.com/u/Ananya1710/", 
    "Kuldeep Sharma" : "https://leetcode.com/u/Kuldeepsharma5836/", 
    "Shubh Varshney" : "https://leetcode.com/u/shubh0104/", 
    "Aditey rai" : "https://leetcode.com/u/Aditey19/", 
    "Vanshika Raghav" : "https://leetcode.com/u/vanshikaraghav_22/", 
    "Deepak Fauzdar" : "https://leetcode.com/u/BoldCarnival/", 
    "Hemant vishu" : "https://leetcode.com/u/hemantvishu14/", 
    "Himanshu Raghav" : "https://leetcode.com/u/himanshud310/", 
    "Mukul Verma" : "https://leetcode.com/u/mukulverma_cs22/", 
    "Saket Maheshwari" : "https://leetcode.com/u/saakkeett/", 
    "VAISHNAVI SHARMA" : "https://leetcode.com/u/sharma_vaishnaviii/", 
    "Bharat Singh" : "https://leetcode.com/u/Bharat_bhagaur_008/", 
    "Saksham" : "https://leetcode.com/u/saxenaboysaksham/", 
    "HARSH PATHAK" : "https://leetcode.com/u/Harsh-1808/", 
    "upendra sisodiya" : "https://leetcode.com/u/sirfupendra/", 
    "Himanshu Singh" : "https://leetcode.com/u/happy04/", 
    "BHANU PRATAP SINGH" : "https://leetcode.com/u/bhanupratap_45/", 
    "Lakshya Dwivedi" : "https://leetcode.com/u/kamina_69/", 
    "Narendra Singh" : "https://leetcode.com/u/narendrasingh1718/",
    }


    const express = require('express');
    const fs = require('fs');

const cors = require('cors'); // Import cors
    const axios = require('axios');
    const app = express();
    const port = 3001;


app.use(cors());
    
    // const studs = {
    //     "Akrishna Agnihotri": "https://leetcode.com/u/Akrishna_Agnihotri/",
    //     "Arpit Saxena": "https://leetcode.com/u/iarpitsaxena/",
    //     "Jeet Thakurela": "https://leetcode.com/u/jeete1singh/",
    //     "Hardik Gupta": "https://leetcode.com/u/17s3WycoRL/",
    // };
    
    // Function to fetch and save student data
    async function fetchAndSaveData() {
        const studentsData = [];
    
        for (const [name, profileLink] of Object.entries(studs)) {
            let username = profileLink.split('/u/')[1];
            if (username[username.length - 1] === '/') username = username.substring(0, username.length - 1);
    
            try {
                const response = await axios.get(`https://leetcodeapi-v1.vercel.app/${username}`);
                const data = response.data;
    
                if (data) {
                    const student = {
                        username,
                        totalSolved: data[username].submitStatsGlobal.acSubmissionNum[0].count || 0,
                        easySolved: data[username].submitStatsGlobal.acSubmissionNum[1].count || 0,
                        mediumSolved: data[username].submitStatsGlobal.acSubmissionNum[2].count || 0,
                        hardSolved: data[username].submitStatsGlobal.acSubmissionNum[3].count || 0,
                    };
                    // console.log(student);
                    studentsData.push(student);
                }
            } catch (error) {
                console.error(`Error fetching data for ${username}:`, error);
            }
        }
    
        // Sort students by totalSolved in descending order
        studentsData.sort((a, b) => b.totalSolved - a.totalSolved);
    
        fs.writeFileSync('data.json', JSON.stringify(studentsData, null, 2));
        console.log('Student data updated and saved to data.json');
    }
    
    // Endpoint to serve the student data
    app.get('/data', (req, res) => {
        res.sendFile(__dirname + '/data.json');
    });
    
    // Initial fetch and save
    fetchAndSaveData();
    
    // Refresh data every hour
    setInterval(fetchAndSaveData, 60 * 60 * 1000);
    
    // Start the server
    app.listen(port, () => {
        console.log(`Server is running at http://localhost:${port}`);
    });
    
